language: node_js
node_js:
- '0.11'
- '0.10' 
deploy:
  provider: firebase
  token:
    secure: "T2tS086MHq1mPIAzs+JfmT2Egh5pMbw+UyhCA6vpBIcobfMFFOuyXy/TdBOZqT3d25K5GdlSTMmFyXUYhXJ5Wyllrl1uImfQq7aQhDQTc62/XZiDHYQsEjId4Ai4lW+BqnvKpRFfBf74coOaUCZLAP7JolH0IQB6nmDG7Pu791alJ57uo+plIJuL73Fk6KcU6PZ/0QpDktG5axM1jAZqFT9+/R+CaBybWDU0F62rjIOp+mtHzBqqEU23CmoVvg2uGkcFPggF1K3M4xn8oheyk3pZjen8UihDhs9SunXhBzQK+/PTQCxWXETyuk7w2KVlldD6RoFwtB3qyasbOdMo1Mh5+2lFn+FOiKE22PvdyKRNAlpi9oOgz02I0HfnL3Yw3fgTz2ZZXxvrJTZ6EAlG+llqVOWr/+1FwVAZqrCdV4Eu7ASdOJ9lniXZO8/EvlxmQUtRzjT2keLMMaepD3bn80g/pQEqC5zTUm6PWS+wK/NOt/GMa5icR68+vXRSh3Ol0/EhG+PCHSlr3zze4RqkydsGYnLUjMewtJLcdel+LrevyIzzDcyy+x15sTwtFsWc1Psn8uJElgPkO3eqUEHfYtEem7Z8jzKFxHdiKbXDyxIR5d3KGRsqlc2Cua0G4QiZjHtLwf2LWwH7o0P7dBMIqC6zLO7TMT1CqHJWCp4cESE="
